[project]
name = "subtask-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Moataz Ahmed", email = "moatazbesher2011@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
subtask-1 = "subtask_1:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
